print("Criar uma lista vazia: ")
L = []
print(L)
print("Adicionar um item ao final da lista:")
L.append(20)
L.append('Jessa')
L.append(35.75)
L.append([30,60,90])
L.append("Fabricio")
print(L)
print("Verificar o tamanho da lista:")
print(len(L))
print("Inserir um item em uma posição específica:")
L.insert(0,"Araujo")
print(L)
print("Remover um valor e excluir o primeiro a aparecer:")
L.remove("Araujo")
print(L)
print("Remover um valor em uma posição específica")
L.pop(len(L)-1)
print(L)

